### ISSUE TITLE
Upgrading to v1.12.0

### ISSUE THREAD

**Issue by firefly21** [joliss/jquery-ui-rails#103]
Please add this version to the gem. I'd like to use jQuery 3, which has a bug with v1.11.4 in the tooltip. This is fixed in v1.12.0

**Comment by medBouzid** [comment]
I also had an error with selectMenu using jQuery 3 so I went back to an old jQuery version, at the same I am not sure the new jquery-ui version will break any of my existing code so I would like to upgrade slowly but surely

**Comment by obfuscoder** [comment]
I'd like to have this update as well. There are known incompatibility issues with JQueryUI 1.11.4 and JQuery 3.0.0.

See https://github.com/jquery/jquery/issues/3181

The README of jquery-ui-rails states that we ought to use jquery-rails in version 3.0.0, but due to this issue, this is not possible.
