### ISSUE TITLE
"define is not defined" error after update to 6.0.0

### ISSUE THREAD

**Issue by lakehouseru** [joliss/jquery-ui-rails#108]
Hello,

I'm getting "define is not defined" Javascript error after update to 6.0.0 from jquery ui core.js 

This error breaks app after assets compile.

**Comment by robertleelittleiii** [comment]
I am seeing the same issue. Had to role gem back to prev version.

**Comment by bradpotts** [comment]
Getting the same error had to roll back as well.

**Comment by jaymac28** [comment]
What  version did you all roll back to? I'm at 5.0.5 and seem still be getting the error.

**Comment by Blogger11** [comment]
I am getting this error as well

**Comment by joliss** [comment]
@Borzik, can you take a look and investigate please?

**Comment by Borzik** [comment]
@joliss ok, will do it soon.

**Comment by Blogger11** [comment]
I had to roll back to gem 'jquery-ui-rails', '5.0.5'

**Comment by Borzik** [comment]
@joliss this is caused by jquery-ui's [core.js](https://github.com/jquery/jquery-ui/blob/master/ui/core.js) file. It is deprecated, and it is an index file for jquery-ui core, but at the same time it's the only file that does not ensure that `define` function exists (all other files have `if ( typeof define === "function" ) { define() }` wrapper for safety).

**Comment by joliss** [comment]
This should be fixed in 6.0.1 thanks to @Borzik's fix!
