### ISSUE TITLE
Include custom theme

### ISSUE THREAD

**Issue by arjunmenon** [joliss/jquery-ui-rails#65]
hi
i got a custom theme made from the theme roller. How can i make it the default?

**Comment by rosenfeld** [comment]
This should be possible. Just create your theme css file under app/assets/stylesheets/jquery-ui/theme.css. You can simply add some sprockets require directives there to load your custom theme I think if you prefer rather than renaming your theme to theme.css. This will override the theme.css bundled with this gem. If that doesn't work please let me know and I'll reopen the ticket.
