### ISSUE TITLE
jQuery ui theme requirement

### ISSUE THREAD

**Issue by banesto** [joliss/jquery-ui-rails#94]
I would advise to remove jquery ui theme requirement in ui widget files as in my case I am using a different theme and the original theme is breaking the design. I think it wouldn't be too hard for application developer to make theme inclusion specifically if needed in application.css.

**Comment by rosenfeld** [comment]
I don't understand, could you please be more specific? If you don't want to use the bundled jQuery UI theme simply do not require them in your css files. This gem won't do any "require" automatically.

**Comment by banesto** [comment]
I mean if I require jquery.ui.datepicker, then ui theme gets also included. But I think it should be optional.

**Comment by rosenfeld** [comment]
If you simply require the datepicker in your JS, no CSS will be included. If you don't want to use the bundled theme simply do not require any bundled CSS in your css files. I still don't understand your request...

**Comment by banesto** [comment]
I am referring to this line https://github.com/joliss/jquery-ui-rails/blob/master/app/assets/stylesheets/jquery-ui/datepicker.css#L13

I think it should not be there and shoulde be up to developer to include theme file.

**Comment by rosenfeld** [comment]
Ah, I got it, there's a quick fix for what you want. Just create an empty jquery-ui/theme.css in your app/assets/stylesheets and the bundled theme will be ignored.

**Comment by banesto** [comment]
Neat trick, but wouldn't removing that theme requiry make more sense?

**Comment by rosenfeld** [comment]
I don't think there's a right TM path here. It's a matter of preferences mostly. I think most people will use the default theme, so asking them for adding another require in their CSS doesn't sound better to me, but of course, this is my personal taste. Since those using a different theme are not the majority, I think it's fine for them to `touch app/assets/styleheets/jquery-ui/theme.css` (and a mkdir -p before) since they are also taking some extra effort to choose another theme anyway... But anyway, it's not me the one you should try to convince to adopt your preferences. You should talk do @joliss instead.

**Comment by banesto** [comment]
I understand that. I'm just trying to open discussion about this, because I think it's more easier to add one line for a theme if it's really required than making empty files - but that's just my opinion.

**Comment by rosenfeld** [comment]
I agree that adding an extra line is easier than creating empty files, although both are trivial. But that's not the question. I think that the easiest path should be for those sticking with the defaults. For most people that means using the default theme and what you are requesting is to request those to add an extra line o their CSS than what they currently do. But this is just part of the problem. It could be a minor problem if we were discussing about the initial release of this gem. But now we would only be able to perform that change in the next major release because it breaks backward compatibility. Another perspective is that datepicker.css indeed depends on a theme. So, maybe, the best approach would to actually save your new theme inside `app/assets/stylesheets/jquery-ui/theme.css`. Don't you agree?

**Comment by banesto** [comment]
Yes, I thought about these two things too. I agree, continuity should be highly regarded. As for new theme in override file - feels hacky, but it should work in most non-default cases I suppose. Thanks.

**Comment by rosenfeld** [comment]
For overriding the default theme you might be also interested in this gem: https://github.com/jhilden/jquery-ui-sass-rails
